# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'weibo项目1-20160820' do

pod"WeiboSDK", :git =>"https://github.com/sinaweibosdk/weibo_ios_sdk.git"

end